/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bigo;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Sebastian
 */
public class FrmBusqueda extends javax.swing.JFrame {

    DefaultListModel modelo= new DefaultListModel();
    int iteracion,elementos,salir,list=0;
    int elementosvec=0;
    int[] vecDatos = new int[100]; 
    
    /**
     * Creates new form FrmBusqueda
     */
    public FrmBusqueda() {
        initComponents();
    }
    public static int busquedaBinaria(int  vector[], int dato){
  int n = vector.length;
  int centro = 0,inf=0,sup=n-1;
   while(inf<=sup){
     centro=(sup+inf)/2;
     if(vector[centro]==dato)
     {
         inf=1000;
     }
         
     else if(dato < vector [centro] ){
        sup=centro-1;
     }
     else {
       inf=centro+1;
     }
   }
   
   return centro;
 }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAgregar = new javax.swing.JButton();
        btnLineal = new javax.swing.JButton();
        txtBusqueda = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        istNumeros = new javax.swing.JList<>();
        txtNumero = new javax.swing.JTextField();
        btnBinaria = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnLineal.setText("Busqueda lineal");
        btnLineal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLinealActionPerformed(evt);
            }
        });

        istNumeros.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(istNumeros);

        txtNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroActionPerformed(evt);
            }
        });

        btnBinaria.setText("Busqueda binaria");
        btnBinaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBinariaActionPerformed(evt);
            }
        });

        jButton2.setText("Ordenamiento por selección ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Ordenamiento por inserción");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Ordenamiento por combianción");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                    .addComponent(txtBusqueda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLineal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBinaria, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnAgregar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAgregar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLineal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBinaria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        modelo.addElement(txtNumero.getText());
        istNumeros.setModel(modelo);
        elementos++;
        txtNumero.setText("");
        
        
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void txtNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroActionPerformed

    private void btnLinealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLinealActionPerformed

        while(iteracion<elementos && salir==0)
        {
            istNumeros.setSelectedIndex(iteracion);
            if(istNumeros.getSelectedValue().toString().equals(txtBusqueda.getText()))
            {
                JOptionPane.showMessageDialog(null,"Número de iteraciones " +iteracion);
                salir=1;
            }
            iteracion++;
        }
    }//GEN-LAST:event_btnLinealActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
              int seleccion, comparar, menor, pos, aux;
          for ( list=0;list<elementos;list++)
        {
            istNumeros.setSelectedIndex(iteracion);
            vecDatos[list]=Integer.parseInt(istNumeros.getSelectedValue());
            iteracion++;
        }
        iteracion=0;      
       
          for (seleccion=0;seleccion<elementos-1;seleccion++) 
          { 
            menor = vecDatos[seleccion]; 
            pos = seleccion; 
            for (comparar=seleccion+1;comparar<elementos;comparar++)
                { 
                if (vecDatos[comparar]<menor) 
                   { 
                    menor=vecDatos[comparar]; 
                    pos=comparar;
                   }
                }
                if (pos!=seleccion)
                { 
                    aux = vecDatos[seleccion];
                    vecDatos[seleccion]=vecDatos[pos];
                    vecDatos[pos]=aux;
                    iteracion++;
                }
               
          }         
 String vec1[]=new String[100];
 
 
modelo.addElement("Ordenado es: ");
      istNumeros.setModel(modelo);
           for( list=0;list<elementos;list++)
          {
              
            vec1[list]=String.valueOf(vecDatos[list]);  
             modelo.addElement(vecDatos[list]);
      istNumeros.setModel(modelo);

          }
          
          JOptionPane.showMessageDialog(null, iteracion);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         for ( list=0;list<elementos;list++)
        {
            istNumeros.setSelectedIndex(iteracion);
            vecDatos[list]=Integer.parseInt(istNumeros.getSelectedValue());
            iteracion++;
        }
        iteracion=0;
       
    int inserccion, anterior,aux;
   
    for (inserccion = 1; inserccion < elementos; inserccion++)
    { 
        aux = vecDatos[inserccion]; 
        anterior = inserccion - 1;
        while ((anterior >= 0) && (aux < vecDatos[anterior]))
        { 
            vecDatos[anterior + 1] = vecDatos[anterior];       
            anterior--;  
            iteracion++;
        }
        vecDatos[anterior + 1] = aux; 
    }
         String vec1[]=new String[100];
 
 
modelo.addElement("Ordenado es: ");
      istNumeros.setModel(modelo);
 
 
 
          for( list=0;list<elementos;list++)
          {
              
            vec1[list]=String.valueOf(vecDatos[list]);  
             modelo.addElement(vecDatos[list]);
      istNumeros.setModel(modelo);

          }
    
        
        JOptionPane.showMessageDialog(null, iteracion);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnBinariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBinariaActionPerformed
        for ( list=0;list<elementos;list++)
        {
            istNumeros.setSelectedIndex(iteracion);
            vecDatos[list]=Integer.parseInt(istNumeros.getSelectedValue());
            iteracion++;
        }
        iteracion=0;
    
       int seleccion, comparar, menor, pos, aux;
         for (seleccion=0;seleccion<elementos-1;seleccion++) 
          { 
            menor = vecDatos[seleccion]; 
            pos = seleccion; 
            for (comparar=seleccion+1;comparar<elementos;comparar++)
                { 
                if (vecDatos[comparar]<menor) 
                   { 
                    menor=vecDatos[comparar]; 
                    pos=comparar;
                   }
                }
                if (pos!=seleccion)
                { 
                    aux = vecDatos[seleccion];
                    vecDatos[seleccion]=vecDatos[pos];
                    vecDatos[pos]=aux;
                    
                }
               
          }
        
  
  int valorBuscado = Integer.parseInt(txtBusqueda.getText());

  int largo = elementos;
  int centro=0,inf=0,sup=largo-1;
   while(inf<=sup){
     centro=(sup+inf)/2;
     if(vecDatos[centro]==valorBuscado)
     {
         iteracion++;
         inf=1000;
     }
         
     else if(valorBuscado < vecDatos [centro] ){
        sup=centro-1;
        iteracion++;
     }
     else {
       inf=centro+1;
       iteracion++;
     }
   }
   
   
   String vec1[]=new String[100];
 
 
modelo.addElement("Ordenado es: ");
      istNumeros.setModel(modelo);
 
 
 
          for( list=0;list<elementos;list++)
          {
              
            vec1[list]=String.valueOf(vecDatos[list]);  
             modelo.addElement(vecDatos[list]);
      istNumeros.setModel(modelo);

          }
          
          JOptionPane.showMessageDialog(null,"Su posicion es "+centro+" con un número de  "+iteracion+" iteraciones");
 
      System.out.print(centro);
    }//GEN-LAST:event_btnBinariaActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        for ( list=0;list<elementos;list++)
        {
            istNumeros.setSelectedIndex(iteracion);
            vecDatos[list]=Integer.parseInt(istNumeros.getSelectedValue());
            iteracion++;
        }
        iteracion=0;        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**v
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmBusqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmBusqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmBusqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmBusqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmBusqueda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBinaria;
    private javax.swing.JButton btnLineal;
    private javax.swing.JList<String> istNumeros;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtBusqueda;
    private javax.swing.JTextField txtNumero;
    // End of variables declaration//GEN-END:variables
}
